"""empty message

Revision ID: ac69db71cc53
Revises: 
Create Date: 2018-02-09 12:11:38.869425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac69db71cc53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('minimum_payment', sa.DECIMAL(), nullable=False),
    sa.Column('balance', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('CANCELLED', 'PENDING', 'PAID', name='billstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('table_name', sa.String(length=250), nullable=False),
    sa.Column('risk_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risk_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('edited_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_edit_log')
    op.drop_table('policy')
    op.drop_table('payment')
    op.drop_table('risk_type')
    op.drop_table('customer')
    op.drop_table('bill')
    # ### end Alembic commands ###
